/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Entidade.Aluno;
import apoio.ConexaoBD;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author Elias Flach
 */
public class JfrTelaPrincipal extends javax.swing.JFrame {

    Aluno usuario;

    /**
     * Creates new form JfrTelaPrincipal
     *
     * @param usuario
     */
    public JfrTelaPrincipal(Aluno usuario) {
        this.usuario = usuario;
        initComponents();


    }

    public JfrTelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        BtnCadastroEstabelecimento = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BtnCadastroCliente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnRelComprasCliente = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        MenuManutencao = new javax.swing.JMenuBar();
        jMenuRelatórios = new javax.swing.JMenu();
        MenuRelatorioCompraCliente = new javax.swing.JMenuItem();
        MenuRelEventosValor = new javax.swing.JMenuItem();
        MenuRelEstabelecimentos = new javax.swing.JMenuItem();
        MenuRelUsuarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        BtnCadastroEstabelecimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Estabelecimento.png"))); // NOI18N
        BtnCadastroEstabelecimento.setToolTipText("Cadastro de Estabelecimento");
        BtnCadastroEstabelecimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadastroEstabelecimentoActionPerformed(evt);
            }
        });

        jLabel1.setText("Cadastros");

        BtnCadastroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Cliente.png"))); // NOI18N
        BtnCadastroCliente.setToolTipText("Cadastro de Clientes");
        BtnCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadastroClienteActionPerformed(evt);
            }
        });

        jLabel2.setText("Venda");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Agenda.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Relatórios");

        btnRelComprasCliente.setText("Compras por Cliente");
        btnRelComprasCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelComprasClienteActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jMenuRelatórios.setText("Relatórios");

        MenuRelatorioCompraCliente.setText("Compras por cliente");
        MenuRelatorioCompraCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRelatorioCompraClienteActionPerformed(evt);
            }
        });
        jMenuRelatórios.add(MenuRelatorioCompraCliente);

        MenuRelEventosValor.setText("Eventos com valor determinado ou maior");
        MenuRelEventosValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRelEventosValorActionPerformed(evt);
            }
        });
        jMenuRelatórios.add(MenuRelEventosValor);

        MenuRelEstabelecimentos.setText("Estabelecimentos cadastrados");
        MenuRelEstabelecimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRelEstabelecimentosActionPerformed(evt);
            }
        });
        jMenuRelatórios.add(MenuRelEstabelecimentos);

        MenuRelUsuarios.setText("Usuarios cadastrados");
        MenuRelUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRelUsuariosActionPerformed(evt);
            }
        });
        jMenuRelatórios.add(MenuRelUsuarios);

        MenuManutencao.add(jMenuRelatórios);

        jInternalFrame1.setJMenuBar(MenuManutencao);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(BtnCadastroEstabelecimento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addGap(58, 58, 58)
                                        .addComponent(jLabel2))
                                    .addComponent(BtnCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(228, 228, 228)
                                .addComponent(jLabel1))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(232, 232, 232)
                                .addComponent(jLabel3))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnRelComprasCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 182, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnCadastroEstabelecimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnCadastroCliente))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(btnRelComprasCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(btnSair)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(524, 647));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCadastroEstabelecimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastroEstabelecimentoActionPerformed
//        DlgCadastroEstabelecimento dlg = new DlgCadastroEstabelecimento(this, true);
//        dlg.setLocationRelativeTo(this);
//        dlg.setVisible(true);
    }//GEN-LAST:event_BtnCadastroEstabelecimentoActionPerformed

    private void BtnCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastroClienteActionPerformed
//        DlgCadastroCliente dlg = new DlgCadastroCliente(this, true);
//        dlg.setLocationRelativeTo(this);
//        dlg.setVisible(true);
    }//GEN-LAST:event_BtnCadastroClienteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//        JfrIngressoVenda p = new JfrIngressoVenda();
//        p.setVisible(true);
//        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void MenuRelatorioCompraClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRelatorioCompraClienteActionPerformed
//        DlgRelatorioClientes dlg = new DlgRelatorioClientes(this, true);
//        dlg.setLocationRelativeTo(this);
//        dlg.setVisible(true);
    }//GEN-LAST:event_MenuRelatorioCompraClienteActionPerformed

    private void MenuRelEventosValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRelEventosValorActionPerformed
//        DlgRelatorioValorShow dlg = new DlgRelatorioValorShow(this, true);
//        dlg.setLocationRelativeTo(this);
//        dlg.setVisible(true);
    }//GEN-LAST:event_MenuRelEventosValorActionPerformed

    private void btnRelComprasClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelComprasClienteActionPerformed
//        DlgRelatorioClientes dlg = new DlgRelatorioClientes(this, true);
//        dlg.setLocationRelativeTo(this);
//        dlg.setVisible(true);
    }//GEN-LAST:event_btnRelComprasClienteActionPerformed

    private void MenuRelEstabelecimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRelEstabelecimentosActionPerformed
//        try {
//            // Compila o relatorio
//            JasperReport relatorio = JasperCompileManager.compileReport(getClass().getResourceAsStream("/Relatórios/rel_estabelecimentos.jrxml"));
//
//            // Mapeia campos de parametros para o relatorio, mesmo que nao existam
//            Map parametros = new HashMap();
//
//            // Executa relatorio
//            JasperPrint impressao = JasperFillManager.fillReport(relatorio, parametros, ConexaoBD.getInstance().getConnection());
//
//            // Exibe resultado em video
//            this.dispose();
//            JasperViewer.viewReport(impressao, false);
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Erro ao gerar relatório: " + e);
//        }
    }//GEN-LAST:event_MenuRelEstabelecimentosActionPerformed

    private void MenuRelUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRelUsuariosActionPerformed
//        try {
//            // Compila o relatorio
//            JasperReport relatorio = JasperCompileManager.compileReport(getClass().getResourceAsStream("/Relatórios/rel_usuarios.jrxml"));
//
//            // Mapeia campos de parametros para o relatorio, mesmo que nao existam
//            Map parametros = new HashMap();
//
//            // Executa relatorio
//            JasperPrint impressao = JasperFillManager.fillReport(relatorio, parametros, ConexaoBD.getInstance().getConnection());
//
//            // Exibe resultado em video
//            this.dispose();
//            JasperViewer.viewReport(impressao, false);
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Erro ao gerar relatório: " + e);
//        }
    }//GEN-LAST:event_MenuRelUsuariosActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfrTelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCadastroCliente;
    private javax.swing.JButton BtnCadastroEstabelecimento;
    private javax.swing.JMenuBar MenuManutencao;
    private javax.swing.JMenuItem MenuRelEstabelecimentos;
    private javax.swing.JMenuItem MenuRelEventosValor;
    private javax.swing.JMenuItem MenuRelUsuarios;
    private javax.swing.JMenuItem MenuRelatorioCompraCliente;
    private javax.swing.JButton btnRelComprasCliente;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton jButton2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenuRelatórios;
    // End of variables declaration//GEN-END:variables
}
